#!/usr/bin/env bash

# author     :  Altertech Group, http://www.altertech.com/
# copyright  :  Copyright (C) 2019 Altertech Group
# license    :  Apache License 2.0
# version:   :  1.0.0

if [ ! -f app/src/main/java/com/altertech/evahi/AppConfig.java ]; then
  echo "Please start this script in evaHI directory"
  exit 3
fi

shopt -s extglob

_CONFIG=()
_SECTIONS=
_PROP=

classname=
name=
version=
versioncode=
copyright=
icon=
icon_round=

configurable=yes
authentication=yes
https=
address=
port=

PAUSE=1

CONFIG_FILE=./prepare.ini
DIRECTORY=


function parseIniFile() {
    local LINE=""
    local SECTION=""
    local KEY=""
    local VALUE=""

    local IFS=""

    while read LINE 
    do
        LINE=${LINE%%[;#]*}
        LINE=${LINE%%*( )}

        if [[ -n $KEY && $LINE =~ ^[[:space:]]+(.+) ]]
        then
            VALUE+=" ${BASH_REMATCH[1]}"
        else
            if [[ -n $KEY ]]
            then
                _CONFIG=(${_CONFIG[@]} "${SECTION}.${KEY}" "${VALUE}")
                KEY=""
                VALUE=""
            fi

            if [[ $LINE =~ ^\[([[:alnum:]]+)\] ]]
            then
                SECTION=${BASH_REMATCH[1]}
                _SECTIONS="${_SECTIONS} ${SECTION}"
                KEY=""
            elif [[ $LINE =~ ^([^[:space:]]+)[[:space:]]*=[[:space:]]*(.+) ]]
            then 
                KEY=${BASH_REMATCH[1]}
                VALUE="${BASH_REMATCH[2]}"
            fi
        fi
    done

    if [[ -n $KEY ]]
    then
        _CONFIG=(${_CONFIG[@]} "${SECTION}.${KEY}" "${VALUE}")
    fi
}

function getProperty() {
	_PROP=""
    local -i i
    local KEY=$1
    for ((i=0; i<${#_CONFIG[@]}; i+=2))
    do
        if [[ ${_CONFIG[$i]} =~ ^\.?${KEY} ]]
        then
            _PROP=${_CONFIG[((i+1))]}
            return 0
        fi
    done
    return 1
}

function showHelp() {
cat <<EOF
Usage: prepare <-D dir> [-f config] [-q]

    -D            directory to store prepared app in
    -f            configuration file (default: ./prepare.ini)
    -q            don't ask any questions, just do it

    --icon        launcher icon (requires ImageMagick)
    --icon-round  launcher round icon (both must be specified)

EOF
}


while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -f)
            CONFIG_FILE="$2"
            shift
            shift
        ;;
        -D) DIRECTORY="$2"
            shift
            shift
        ;;
        -q) PAUSE=
            shift
        ;;
        --icon) icon="$2"
          shift
          shift
          ;;
        --icon-round) icon_round="$2"
          shift
          shift
          ;;
        -h|--help) showHelp
            exit 0
        ;;
        *)
            echo "Unknown option: ${key}"
            showHelp
            exit -1
        ;;
    esac
done

if [ ! -f ${CONFIG_FILE} ]; then
    echo "config not found: ${CONFIG_FILE}. Use -f to specify custom config file, -h for help"
    exit 3
fi

if [ ! ${DIRECTORY} ]; then
  echo "Directory not specified"
  showHelp
  exit 3
fi

if [ -d ${DIRECTORY} ]; then
  echo "Directory ${DIRECTORY} already exists"
  echo "Aborting"
  exit 4
fi

if [ ${icon} ] || [ ${icon_round} ]; then
  if [ ! ${icon} ]; then
    echo "Icon not specified"
    echo "Aborting"
    exit 4
  fi
  if [ ! ${icon_round} ]; then
    echo "Round icon not specified"
    echo "Aborting"
    exit 4
  fi
  which convert > /dev/null
  if [ $? -ne 0 ]; then
    echo "Icons specified but ImageMagick not found"
    echo "Aborting"
    exit 4
  fi
  if [ ! -f ${icon} ]; then
    echo "File not found: ${icon}"
    exit 4
  fi
  if [ ! -f ${icon_round} ]; then
    echo "File not found: ${icon_round}"
    exit 4
  fi
fi

parseIniFile < $CONFIG_FILE

getProperty app.classname
classname=${_PROP}
getProperty app.name
name=${_PROP}
getProperty app.version
version=${_PROP}
getProperty app.versioncode
versioncode=${_PROP}
getProperty app.copyright
copyright=${_PROP}

getProperty server.configurable
configurable=${_PROP}
getProperty server.authentication
authentication=${_PROP}
getProperty server.https
https=${_PROP}
getProperty server.address
address=${_PROP}
getProperty server.port
port=${_PROP}

if [ ! $classname ]; then
  echo "Class name not specified"
  echo "Aborting"
  exit 5
fi

echo "New evaHI-based app is ready to be created"
echo
echo "App directory: ${DIRECTORY}"
echo "Class name: ${classname}"
echo "App name: ${name}"
echo "App version: ${version}"
echo "App version code: ${versioncode}"
echo "App copyright: ${copyright}"
echo
echo "Server configurable: ${configurable}"
echo "Use basic authentication: ${authentication}"
echo "Use HTTPS: ${https}"
echo "Default server address: ${address}"
echo "Default server port: ${port}"

if [ ! ${icon} ]; then
  echo "Launcher icon not set"
else
  echo "Launcher icon: ${icon}"
  echo "Launcher round icon: ${icon_round}"
fi

echo

if [ $PAUSE ]; then
  echo "Check if everything is correct, press ENTER to continue, Ctrl+C to abort"
  read
fi

echo "Creating app directory"
mkdir -p ${DIRECTORY} || exit 1
echo "Copying app files..."
cp -prf * ${DIRECTORY} || exit 1
cd ${DIRECTORY} || exit 1
echo "Configuring..."
sed -i "s/<string name=\"app_name\">EvaHI</<string name=\"app_name\">${name}</g" app/src/main/res/values/strings.xml || exit 1
sed -i "s/String NAME = \"\", VERSION = \"\", COPYRIGHT = \"\";/String NAME = \"${name}\", VERSION = \"${version}\", COPYRIGHT = \"${copyright}\";/g" app/src/main/java/com/altertech/evahi/AppConfig.java || exit 1
[ "x${configurable}" = "xyes" ] && C=false || C=true
[ "x${https}" = "xyes" ] && H=true || H=false
sed -i "s/ServerConfig(false, false, \"\", 443);/ServerConfig(${C}, ${H}, \"${address}\", ${port});/g" app/src/main/java/com/altertech/evahi/AppConfig.java || exit 1
[ "x${authentication}" = "xyes" ] && A=true || A=false
sed -i "s/boolean AUTHENTICATION = true;/boolean AUTHENTICATION = ${A};/g" app/src/main/java/com/altertech/evahi/AppConfig.java || exit 1
sed -i "s/versionCode .*/versionCode ${versioncode}/g" app/build.gradle || exit 1
sed -i "s/versionName .*/versionName \"${version}\"/g" app/build.gradle || exit 1
echo "Renaming classes..."
find . -type f -exec sed -i "s/com.altertech.evahi/${classname}/g" {} \; || exit 1
mkdir -p app/src/main/java/`echo ${classname} | tr "." "/"` || exit 1
mv -f app/src/main/java/com/altertech/evahi/* app/src/main/java/`echo ${classname} | tr "." "/"`/ || exit 1
rmdir app/src/main/java/com/altertech/evahi || exit 1
rmdir app/src/main/java/com/altertech > /dev/null 2>&1
rmdir app/src/main/java/com > /dev/null 2>&1
rm -f prepare prepare.ini evaHI.iml
rm -rf examples
rm -rf app/build
if [ ${icon} ]; then
  echo "Generating icons..."
  convert -resize 48x48 -unsharp 1x4 ${icon} app/src/main/res/mipmap-mdpi/ic_launcher.png || exit 1
  convert -resize 72x72 -unsharp 1x4 ${icon} app/src/main/res/mipmap-hdpi/ic_launcher.png || exit 1
  convert -resize 96x96 -unsharp 1x4 ${icon} app/src/main/res/mipmap-xhdpi/ic_launcher.png || exit 1
  convert -resize 144x144 -unsharp 1x4 ${icon} app/src/main/res/mipmap-xxhdpi/ic_launcher.png || exit 1
  convert -resize 192x192 -unsharp 1x4 ${icon} app/src/main/res/mipmap-xxxhdpi/ic_launcher.png || exit 1

  convert -resize 48x48 -unsharp 1x4 ${icon_round} app/src/main/res/mipmap-mdpi/ic_launcher_round.png || exit 1
  convert -resize 72x72 -unsharp 1x4 ${icon_round} app/src/main/res/mipmap-hdpi/ic_launcher_round.png || exit 1
  convert -resize 96x96 -unsharp 1x4 ${icon_round} app/src/main/res/mipmap-xhdpi/ic_launcher_round.png || exit 1
  convert -resize 144x144 -unsharp 1x4 ${icon_round} app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png || exit 1
  convert -resize 192x192 -unsharp 1x4 ${icon_round} app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png || exit 1
fi
echo "-----------------------------------------------"
echo "Completed"
if [ ! ${icon} ]; then
  echo "Don't forget to customize app icons (app/src/main/res)"
fi
exit 0
