package com.altertech.evahi.core;

/**
 * Created by oshevchuk on 13.02.2019
 */
interface AppConstants {

    String KEY_SETTINGS_SERVER_SCHEME = "KEY_SETTINGS_SERVER_SCHEME_B";
    String KEY_SETTINGS_SERVER_ADDRESS = "KEY_SETTINGS_SERVER_ADDRESS";
    String KEY_SETTINGS_SERVER_PORT = "KEY_SETTINGS_SERVER_PORT";
    //String KEY_SETTINGS_SERVER_PAGE = "KEY_SETTINGS_SERVER_PAGE";
    //String KEY_SETTINGS_SERVER_LANDSCAPE_PAGE = "KEY_SETTINGS_SERVER_LANDSCAPE_PAGE";
    String KEY_SETTINGS_SERVER_CONFIG = "KEY_SETTINGS_SERVER_CONFIG";

    String KEY_SETTINGS_USER_NAME = "KEY_SETTINGS_USER_NAME";
    String KEY_SETTINGS_USER_PASSWORD = "KEY_SETTINGS_USER_PASSWORD";

}
